### ISSUE TITLE
radvd doesn't announce prefix added at runtime

### ISSUE THREAD

**Issue by cm-rudolph** [reubenhwk/radvd#53] opened 2016-01-07 19:18 UTC
radvd recognizes (and immediately sends out an advertisement) a new prefix that gets configured on an interface. But when using the special configuration prefix `::/64`, it still announces the prefixes that were present when starting radvd.
Sending a `SIGHUP` causes to reread the configuration. After that the new prefix gets announced, too.

It seems that deleting an address doesn't remove it from following announcements, too.

**Comment by reubenhwk** [comment] 2016-01-07 21:00
Using the latest version?

**Comment by cm-rudolph** [comment] 2016-01-08 09:44
Snapshot ;-)

**Comment by cm-rudolph** [comment] 2016-01-08 10:32
Some debug output (I added the `received message of type %d" debug output to see which rtnetlink messages get processed by radvd):

At startup `eth0` has a link-local and the IP address `2001:db8:ef10:30fc::1/64`.
radvdump outputs (shortened, parameters stripped, link-local prefix removed):

    interface eth1
    {
            prefix 2001:db8:ef10:30fc::/64
            {
            };
    };

Then I deleted the IP using `ip -6 addr del 2001:db8:ef10:30fc::1/64 dev eth1`
radvd debug output is 

    [Jan 08 11:13:08] radvd (19754): netlink: received message of type 21
    [Jan 08 11:13:09] radvd (19754): ioctl(SIOCGIFFLAGS) succeeded on eth1
    [Jan 08 11:13:09] radvd (19754): eth1 is up
    [Jan 08 11:13:09] radvd (19754): eth1 is running
    [Jan 08 11:13:09] radvd (19754): eth1 supports multicast

Shortly after reinitialization of eth1 radvdump still outputs

    interface eth1
    {
            prefix 2001:db8:ef10:30fc::/64
            {
            };
    };

Then I added another IP address (last part of prefix is now d instead of c) using `ip -6 addr add 2001:db8:ef10:30fd::1/64 dev eth1`.
radvd debug output:

    [Jan 08 11:13:38] radvd (19754): netlink: received message of type 20
    [Jan 08 11:13:40] radvd (19754): netlink: received message of type 20
    [Jan 08 11:14:40] radvd (19754): netlink: received message of type 20
    [Jan 08 11:14:41] radvd (19754): ioctl(SIOCGIFFLAGS) succeeded on eth1
    [Jan 08 11:14:41] radvd (19754): eth1 is up
    [Jan 08 11:14:41] radvd (19754): eth1 is running
    [Jan 08 11:14:41] radvd (19754): eth1 supports multicast

And radvdump still outputs

    interface eth1
    {
            prefix 2001:db8:ef10:30fc::/64
            {
            };
    };

Message type 20 is `RTM_NEWADDR` and type 21 is `RTM_DELADDR`.

**Comment by mhanor** [comment] 2016-01-08 11:02
See the issue #39

**Comment by reubenhwk** [comment] 2016-08-19 06:53
duplicate of #39

**Closed by reubenhwk** 2016-08-19 06:53 UTC
